matrix:
  include:
  - language: cpp
    sudo: enabled
    before_install:
      - sudo apt-get update
      - sudo apt-get install -y gcc liblapack-dev cmake libfftw3-dev libgtest-dev
      - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
      - pip install numpy --user
      - pip install scipy --user
      - sudo apt-get install -y libopenmpi-dev openmpi-bin
    install:
      - mkdir build
      - cd build
      - cmake -DTesting=ON ../
      - VERBOSE=1 make 
    script:
      - export OMP_NUM_THREADS=1
      - make test ARGS='-V'

 
